
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { config, getRequiredConfig } from "./src/config/config";

export default defineConfig({
  // Point Prisma to the folder containing multiple .prisma files
  schema: "src/backend/prisma/schema/",
  migrations: {
    path: "src/backend/prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: getRequiredConfig(config.database.url, "DATABASE_URL"),
    directUrl: getRequiredConfig(config.database.directUrl, "DIRECT_URL"),
  },
});
