import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';

const prisma = new PrismaClient();

interface SeedPost {
  title: string;
  body: string;
  labels: string[];
}

const posts: SeedPost[] = [
  // ── Café: Cultivo ──
  { title: 'Manejo integrado de la roya del cafeto (Hemileia vastatrix)', body: 'La roya del cafeto es la enfermedad más devastadora del cultivo de café en Colombia. Se presenta como pólvora amarilla-anaranjada en el envés de las hojas, provocando defoliación prematura y pérdidas de hasta el 40% en producción. El manejo integrado combina: (1) siembra de variedades resistentes como Castillo® o Colombia, (2) control químico con fungicidas cúpricos y triazoles en épocas de alta precipitación, (3) manejo agronómico con podas fitosanitarias y regulación de sombrío al 30-40%, y (4) monitoreo quincenal con la escala de evaluación propuesta por Cenicafé. Se recomienda aplicar caldos bordelés al 1% cada 15 días durante el pico de lluvias y usar fungicidas sistémicos como epoxiconazol en rotación.', labels: ['café', 'plagas', 'cultivos'] },
  { title: 'Establecimiento de semillero de café variedad Castillo', body: 'Para establecer un semillero de café variedad Castillo se recomienda usar almácigos con sustrato desinfectado compuesto por 70% tierra negra y 30% materia orgánica compostada. Las semillas deben seleccionarse de árboles elite con producción superior a 2.5 kg de café pergamino por año. La siembra se realiza en eras de 1.2 m de ancho a una profundidad de 1.5 cm. El semillero debe ubicarse bajo media sombra (50%) con riego moderado dos veces por día. La germinación inicia a los 35-45 días y el transplante a bolsa se hace cuando las plántulas presentan 4-6 hojas verdaderas (aproximadamente a los 4 meses). Se recomienda fertilización con DAP (10g/m²) a los 30 días de germinación.', labels: ['café', 'cultivos'] },
  { title: 'Fertilización del café según análisis de suelos', body: 'La fertilización del café debe basarse estrictamente en análisis de suelos, idealmente realizados cada 6 meses. Para cafetales en producción se recomienda aplicar 250-400 kg/ha/año de Nitrógeno, 40-60 kg/ha/año de Fósforo (P2O5) y 200-300 kg/ha/año de Potasio (K2O), fraccionado en 3-4 aplicaciones por año. El cafeto requiere también micronutrientes como Boro (1-2 kg/ha), Zinc (2-3 kg/ha) y Magnesio (15-20 kg/ha). En suelos con pH inferior a 5.0, se debe encalar con 500-1000 kg/ha de cal dolomítica 3 meses antes de la siembra. La fertilización orgánica complementaria con compost (3-5 kg/árbol/año) mejora significativamente la actividad microbiana y la retención de humedad del suelo.', labels: ['café', 'cultivos', 'nutrición'] },
  { title: 'Control de la broca del café (Hypothenemus hampei) con Beauveria bassiana', body: 'La broca del café es la plaga de mayor impacto económico en la caficultura colombiana. El control biológico con Beauveria bassiana ha demostrado eficiencias superiores al 70% cuando se aplica correctamente. Se recomienda aplicar 1 kg de formulación comercial (1x10^12 conidias/kg) disuelto en 200 L de agua por hectárea, con aplicaciones dirigidas al tercio medio del árbol donde se concentra la mayor carga de frutos. Las condiciones óptimas de aplicación son: temperatura entre 22-28°C, humedad relativa >80% y horas de la tarde para evitar radiación UV directa. Se deben realizar 3-4 aplicaciones por ciclo productivo: la primera al inicio de la fructificación (60 días después de floración), la segunda al inicio de grano lechoso y las siguientes según monitoreo.', labels: ['café', 'plagas', 'cultivos'] },
  { title: 'Beneficio húmedo del café: calidad y fermentación controlada', body: 'El beneficio húmedo del café en Colombia determina en gran medida la calidad de la taza. El proceso inicia con el despulpado del fruto maduro (evitando verdes y sobremaduros), seguido de fermentación natural en tanques de concreto o acero inoxidable por 12-18 horas a temperatura ambiente (18-24°C). El punto óptimo de fermentación se determina cuando al introducir un palo de madera, éste deja una marca limpia (prueba del palo). El lavado posterior debe eliminar completamente el mucílago usando agua limpia (relación 1:3 café/agua). El secado se recomienda en patios solares o camas africanas hasta alcanzar 10-12% de humedad, volteando cada 2-3 horas para evitar fermentaciones secundarias.', labels: ['café', 'cultivos', 'cosecha'] },
  { title: 'Control de nematodos en cafetales con plantas antagonistas', body: 'Los nematodos fitoparásitos (Meloidogyne spp., Pratylenchus spp.) causan pérdidas significativas en cafetales colombianos, especialmente en viveros y renovaciones. El uso de plantas antagonistas como Crotalaria juncea y Tagetes erecta (caléndula) ha demostrado reducciones de hasta 60% en poblaciones de nematodos. Se recomienda sembrar Crotalaria como cobertura 3-4 meses antes de establecer el café, incorporándola al suelo al inicio de floración. En cafetales establecidos, la aplicación de materia orgánica (5 kg/árbol de compost enriquecido) estimula la microbiota antagonista del suelo. El manejo integrado incluye también la selección de portainjertos resistentes, como el Aro­tinto, y evitar el movimiento de suelo contaminado entre lotes.', labels: ['café', 'plagas', 'cultivos', 'suelos'] },
  { title: 'Sistemas agroforestales con café: sombrío regulado y diversificación', body: 'Los sistemas agroforestales (SAF) con café ofrecen múltiples beneficios: regulación térmica, conservación de humedad, aporte de materia orgánica y diversificación de ingresos. Las especies de sombrío recomendadas incluyen guamo (Inga edulis), carbonero (Calliandra spp.) y plátano (Musa spp.) para sombrío temporal, y nogal (Cordia alliodora) o cedro (Cedrela odorata) para sombrío permanente. La densidad óptima de sombrío es de 40-60 árboles/ha con una cobertura foliar del 30-40%. El plátano como sombrío temporal proporciona ingresos adicionales durante los primeros 2-3 años mientras el café alcanza plena producción. Se recomienda poda anual de ramas bajas de los árboles de sombrío para regular la entrada de luz.', labels: ['café', 'cultivos'] },
  { title: 'Enfermedades del café: la llaga negra (Rosellinia bunodes) y su manejo', body: 'La llaga negra causada por Rosellinia bunodes es una enfermedad radical del café que se presenta en suelos pesados con mal drenaje. Los síntomas incluyen amarillamiento progresivo, defoliación y muerte descendente de ramas, con presencia de micelio negro en raíces. El manejo integrado incluye: (1) eliminación de árboles afectados con extracción completa de raíces, (2) encalado del suelo para elevar pH a 5.5-6.0, (3) mejora del drenaje con zanjas de coronación, (4) aplicación de Trichoderma harzianum (1 kg/ha) al suelo en el momento de la siembra, y (5) evitar encharcamientos. En lotes con historial de la enfermedad, se recomienda establecer barreras físicas (zanjas de 40 cm de profundidad) alrededor de los focos para evitar la propagación del micelio.', labels: ['café', 'plagas', 'cultivos', 'suelos'] },
  { title: 'Cosecha selectiva de café: criterios de madurez y rendimiento', body: 'La cosecha selectiva del café es fundamental para obtener cafés especiales. Los frutos deben recolectarse manualmente cuando presenten color rojo cereza intenso (variedades tradicionales) o amarillo intenso (variedades como Castillo Amarillo). Se deben rechazar frutos verdes (bajos en azúcares y con alto contenido de clorofila que genera astringencia), sobremaduros (inician fermentación no deseada) y pasilla (frutos secos que aportan sabores a madera). Un recolector experimentado cosecha entre 60-100 kg de café cereza/día. La relación de rendimiento es aproximadamente 5 kg de café cereza para obtener 1 kg de café pergamino seco. Se recomienda realizar entre 4-6 pases por árbol durante la cosecha principal, con intervalos de 15-20 días.', labels: ['café', 'cultivos', 'cosecha'] },
  { title: 'Manejo de arvenses en cafetales: coberturas nobles y control selectivo', body: 'El manejo de arvenses en cafetales debe enfocarse en mantener coberturas vegetales nobles que protejan el suelo sin competir excesivamente con el café. Se recomienda mantener coberturas como kudzú (Pueraria phaseoloides), maní forrajero (Arachis pintoi) o leguminosas nativas, las cuales fijan nitrógeno y controlan la erosión. El control de arvenses agresivas como pasto estrella (Cynodon nlemfuensis) o coquito (Cyperus rotundus) debe realizarse mediante plateo manual alrededor del árbol (radio de 60 cm) y uso de guadaña en calles. Se desaconseja el uso de herbicidas químicos como glifosato por su impacto en la microbiota del suelo y la salud del trabajador. Se recomienda realizar 3-4 controles manuales al año.', labels: ['café', 'cultivos', 'suelos'] },

  // ── Café: Nutrición y Suelos ──
  { title: 'Análisis foliar en café: interpretación de resultados y ajuste de fertilización', body: 'El análisis foliar es una herramienta complementaria al análisis de suelos para ajustar la fertilización del cafeto. La muestra foliar debe tomarse del tercer o cuarto par de hojas de ramas productivas en la parte media del árbol, recolectando 30-40 hojas por lote homogéneo. Los niveles críticos de nutrientes en café son: N 2.8-3.2%, P 0.12-0.18%, K 2.0-2.5%, Ca 0.8-1.2%, Mg 0.25-0.40%, S 0.15-0.25%, B 20-40 ppm, Zn 15-30 ppm, Cu 8-15 ppm, Fe 50-150 ppm y Mn 50-200 ppm. Valores fuera de estos rangos indican deficiencias o toxicidades que requieren ajuste del plan de fertilización. Se recomienda realizar análisis foliar cada 2-3 años o cuando se observen síntomas visuales de desbalance nutricional.', labels: ['café', 'nutrición', 'cultivos'] },
  { title: 'Control de la mancha de hierro (Cercospora coffeicola) en café', body: 'Los síntomas de Cercospora coffeicola incluyen manchas circulares de color marrón-rojizo con centro grisáceo y borde púrpura en hojas viejas. La enfermedad se asocia a desbalances nutricionales, especialmente defi­ciencia de potasio y exceso de nitrógeno. El manejo integrado incluye: (1) fertilización balanceada con énfasis en K y Mg, (2) aplicación de fungicidas cúpricos (oxicloruro de cobre 2.5 g/L) cada 15-20 días en épocas de alta humedad, (3) poda de recepa para renovar tejido vegetativo en lotes muy afectados, (4) regulación de sombrío para mejorar aireación. Los fungicidas triazoles como tebuconazol (1 mL/L) también muestran buena eficacia en rotación con productos cúpricos.', labels: ['café', 'plagas', 'cultivos'] },

  // ── Cacao: Cultivo ──
  { title: 'Establecimiento de cultivo de cacao: marcos de siembra y sombrío temporal', body: 'El establecimiento de cacao requiere planificación cuidadosa del sombrío desde el primer día. Se recomienda sembrar plátano hartón (Musa AAB) como sombrío temporal a 3x3 m (1111 plantas/ha) 6 meses antes del cacao. El cacao se siembra a 3x3 m (1111 plantas/ha) en sistema tresbolillo, con hoyos de 40x40x40 cm mejorados con 5 kg de materia orgánica y 200 g de cal dolomítica. Los clones recomendados para Colombia incluyen ICS-95, ICS-39, FSV-41, FEAR-5 y CCN-51. El sombrío permanente se establece con especies como guamo (Inga edulis), búcaro (Erythrina poeppigiana) o laúrel (Cordia alliodora) en densidad de 10-15 árboles/ha. La primera cosecha comercial se obtiene entre los 18-24 meses.', labels: ['cacao', 'cultivos'] },
  { title: 'Manejo integrado de moniliasis (Moniliophthora roreri) en cacao', body: 'La moniliasis es la enfermedad más limitante del cacao en Colombia, causando pérdidas del 30-80% si no se maneja adecuadamente. Los síntomas incluyen manchas marrones aceitosas en frutos jóvenes que evolucionan a una capa blanca cremosa de esporas. El manejo integrado requiere: (1) podas fitosanitarias semanales eliminando frutos enfermos y depositándolos en fosas con cal, (2) podas de ventilación para mantener la copa abierta (menos de 30% de densidad foliar), (3) aplicación de fungicidas cúpricos (2.5 g/L) cada 15 días durante época de lluvias, alternando con fungicidas orgánicos como Bacillus subtilis, (4) cobertura de frutos con caldo bordelés al 1% en etapas tempranas de desarrollo. La frecuencia de cosecha debe ser cada 7-10 días para reducir el inóculo en el lote.', labels: ['cacao', 'plagas', 'cultivos'] },
  { title: 'Control de escoba de bruja (Moniliophthora perniciosa) en cacao', body: 'La escoba de bruja causa deformación de brotes, cojines florales y frutos, con pérdidas de hasta 50%. Los síntomas incluyen hipertrofia de yemas terminales (escobas vegetativas) y deformación de frutos con manchas verdes oscuras (escobas de fruto). El manejo integrado se basa en: (1) poda fitosanitaria cada 15-20 días eliminando escobas a 30 cm del punto de infección, (2) aplicación de fungicida cúprico (oxicloruro de cobre 3 g/L) en cojines florales durante la floración principal, (3) uso de clones tolerantes como CCN-51 e ICS-39, (4) manejo de sombrío regulado (máximo 40%) para reducir humedad, (5) aplicación de Trichoderma spp. (10^6 esporas/mL) como biocontrolador. Las escobas deben dejarse en el suelo para permitir la acción de microorganismos antagonistas.', labels: ['cacao', 'plagas', 'cultivos'] },
  { title: 'Fermentación del cacao: perfiles de sabor y control de calidad', body: 'La fermentación del cacao es crucial para desarrollar los precursores de sabor a chocolate. El proceso dura 5-7 días dependiendo del tipo de grano (criollo 2-3 días, trinitario 4-5 días, forastero 5-7 días). Las baba de cacao (mucílago) debe fermentarse en cajones de madera de 60x60x60 cm (capacidad 40-50 kg). Los primeros 2 días se deja reposar sin mover; los días 3 a 7 se realiza volteo cada 24-48 horas para aireación. La temperatura debe alcanzar 45-50°C al tercer día y mantenerse así. La prueba de corte se realiza al finalizar: grano bien fermentado presenta color marrón violáceo uniforme, mientras que grano violeta oscuro indica fermentación incompleta. El secado solar en marquesinas hasta 7-8% de humedad garantiza la estabilidad del producto.', labels: ['cacao', 'cultivos', 'cosecha'] },
  { title: 'Manejo de la pudrición de mazorca (Phytophthora palmivora) en cacao', body: 'La pudrición de mazorca causada por Phytophthora palmivora se manifiesta como manchas marrones acuosas que se extienden rápidamente cubriendo todo el fruto con micelio blanco. El manejo integrado incluye: (1) drenaje adecuado del lote para evitar encharcamientos, (2) poda de formación para evitar contacto de mazorcas entre sí y con ramas, (3) eliminación semanal de frutos enfermos, (4) aplicación preventiva de fungicidas a base de metalaxil + mancozeb (2.5 g/L) cada 21 días en época lluviosa, o Fosetil-Al (3 mL/L) como alternativa sistémica, (5) encalado del suelo (1 ton/ha) para reducir inóculo del suelo. En sistemas agroecológicos, las aspersiones con caldo bordelés al 2% cada 8 días muestran buena eficacia preventiva.', labels: ['cacao', 'plagas', 'cultivos'] },
  { title: 'Clones de cacao recomendados para la región del Pacífico colombiano', body: 'La selección clonal es fundamental para el éxito del cultivo de cacao. Para la región Pacífico colombiana se recomiendan los clones: FSV-41 (alto rendimiento, 2.5 kg/árbol/año, tolerancia a moniliasis), ICS-39 (buena calidad de sabor, 1.8 kg/árbol/año), CCN-51 (alta producción, 3.5 kg/árbol/año, tolerante a escoba de bruja), FEAR-5 (grano grande, 2.2 kg/árbol/año) y TCS-01 (adaptado a suelos ácidos). La densidad de siembra varía según el clon: 800-1111 plantas/ha para clones vigorosos (CCN-51) y 1200-1500 plantas/ha para clones compactos (FSV-41). Se recomienda plantar al menos 4 clones diferentes en el lote para asegurar polinización cruzada, con distancia máxima de 20 m entre clones.', labels: ['cacao', 'cultivos'] },
  { title: 'Control de hormiga arriera (Atta cephalotes) en cultivos de cacao', body: 'La hormiga arriera es una plaga defoliadora importante en cacao, especialmente en la fase de establecimiento. El control integrado incluye: (1) localización de hormigueros mediante rastreo de senderos, especialmente después de lluvias, (2) aplicación de cebos granulados a base de sulfluramida (0.1%) cerca de los nidos activos (3-5 g/hormiguero), (3) siembra de barreras vivas con plantas repelentes como madero negro (Gliricidia sepium) cerca de los nidos, (4) aplicación de hongos entomopatógenos Beauveria bassiana (1x10^12 conidias/ha) en el suelo alrededor del hormiguero, (5) control mecánico de nidos pequeños mediante excavación y exposición de la reina. Se desaconseja el uso de insecticidas de amplio espectro que afectan la fauna benéfica.', labels: ['cacao', 'plagas', 'cultivos'] },
  { title: 'Poda de formación y mantenimiento del cacao', body: 'La poda del cacao es determinante para la productividad y sanidad del cultivo. La poda de formación se realiza en los primeros 2 años, dejando 3-4 ramas principales bien distribuidas (copa abierta tipo candelabro). La poda de mantenimiento anual consiste en: (1) eliminar chupones del tallo principal, (2) cortar ramas secas, enfermas o entrecruzadas, (3) regular la altura máxima a 3-4 metros para facilitar cosecha, (4) eliminar ramas bajas que tocan el suelo. La intensidad de poda debe ser moderada (eliminar máximo 30% de la copa) para evitar estrés y estimular crecimiento vegetativo excesivo. La herramienta debe desinfectarse entre árboles con solución de hipoclorito de sodio al 5% para evitar transmisión de enfermedades.', labels: ['cacao', 'cultivos'] },
  { title: 'Cosecha y postcosecha del cacao: selección de mazorcas y protocolo de calidad', body: 'La cosecha del cacao debe realizarse cada 7-15 días durante la temporada principal, seleccionando solo mazorcas maduras (color amarillo, naranja o rojo según el clon). El corte se hace con tijera podadora, evitando dañar el cojín floral. La clasificación poscosecha separa granos sanos de fermentados y granos vanos (prueba de flotación en agua). El protocolo de calidad exige que las mazorcas sean abiertas dentro de las 48 horas posteriores a la cosecha, utilizando machete de percusión para evitar dañar los granos. El rendimiento promedio de grano seco por mazorca es 30-50 g (equivalente a 10-15 mazorcas por kg de grano seco). La productividad oscila entre 500-1500 kg/ha/año según nivel de manejo.', labels: ['cacao', 'cultivos', 'cosecha'] },

  // ── Plátano: Cultivo ──
  { title: 'Manejo integrado de la sigatoka negra (Mycosphaerella fijiensis) en plátano', body: 'La sigatoka negra es la enfermedad foliar más destructiva del plátano en Colombia. Los síntomas progresan desde pequeñas manchas cloróticas iniciales hasta grandes lesiones necróticas marrón oscuro con bordes cloróticos, reduciendo el área fotosintética. El manejo integrado incluye: (1) aplicación de fungicidas protectantes como mancozeb (2 kg/ha) rotando con triazoles como propiconazol (0.5 L/ha) cada 7-14 días, (2) deshoje sanitario semanal eliminando las tres hojas más viejas y las que presenten más del 50% de área afectada, (3) drenaje del lote para reducir humedad ambiental, (4) fertilización balanceada con potasio (400-500 kg K2O/ha/año) que reduce la severidad de la enfermedad, (5) uso de colinos certificados libres de la enfermedad al establecer nuevas siembras.', labels: ['plátano', 'plagas', 'cultivos'] },
  { title: 'Fertilización del cultivo de plátano para altos rendimientos', body: 'El plátano es extremadamente exigente en nutrientes, especialmente potasio. Los requerimientos nutricionales para una producción de 25-30 ton/ha/año son: N 350-450 kg/ha, P2O5 80-120 kg/ha, K2O 600-800 kg/ha, MgO 60-80 kg/ha, CaO 150-200 kg/ha, S 30-40 kg/ha. El potasio es el elemento más crítico —su deficiencia causa hojas amarillas con necrosis marginal, racimos pequeños y dedos delgados. La fertilización se fracciona en 4-6 aplicaciones anuales, con mayor énfasis en la época de máxima precipitación. Se recomienda complementar con fertilizantes orgánicos como compost (10-15 kg/planta/año) o gallinaza (3-5 kg/planta/año). El análisis de suelos cada año permite ajustar las dosis y detectar deficiencias de micronutrientes como Zinc (Zn) y Boro (B).', labels: ['plátano', 'cultivos', 'nutrición'] },
  { title: 'Control del picudo del plátano (Cosmopolites sordidus) con trampas', body: 'El picudo negro del plátano es la plaga más importante del cultivo a nivel mundial, causando galerías en el cormo que debilitan la planta y facilitan el volcamiento. El monitoreo se realiza con trampas de pseudotallo (cebo fresco) cortado en discos de 15-20 cm, colocados a nivel del suelo entre las plantas. Se revisan semanalmente contando adultos capturados (umbral de acción: 10 adultos/trampa/semana). El control integrado incluye: (1) uso de colinos certificados libres de picudo, (2) trampeo masivo con pseudotallo tratado con Beauveria bassiana (50 g de conidias/trampa), (3) aplicación de nematodos entomopatógenos (Steinernema carpocapsae a 1x10^9 IJ/ha) alrededor del cormo, (4) destrucción de residuos de cosecha para eliminar refugios.', labels: ['plátano', 'plagas', 'cultivos'] },
  { title: 'Manejo de la pudrición acuosa del seudotallo por Erwinia chrysanthemi', body: 'La pudrición acuosa causada por Erwinia chrysanthemi se manifiesta como amarillamiento y colapso repentino de hojas jóvenes, con mal olor característico y exudados bacterianos viscosos en el corte del tallo. Las condiciones predisponentes incluyen exceso de humedad, heridas por herramientas o insectos, y altas temperaturas. El manejo integrado se basa en: (1) eliminación inmediata de plantas enfermas con extracción completa del cormo, (2) desinfección de herramientas con hipoclorito de sodio al 10% entre plantas, (3) mejora del drenaje del suelo, (4) reducción de la fertilización nitrogenada excesiva, (5) aplicación preventiva de bactericidas a base de sulfato de estreptomicina (200 ppm) en épocas de alta incidencia, (6) encalado del suelo para elevar pH a 6.0-6.5.', labels: ['plátano', 'plagas', 'cultivos'] },
  { title: 'Multiplicación rápida de plátano: técnica de cormos segmentados', body: 'La técnica de cormos segmentados permite multiplicar material de siembra de plátano hasta 10 veces más rápido que el método tradicional. Consiste en dividir cormos grandes (1-2 kg) en 4-8 segmentos, cada uno con al menos una yema viable. Los segmentos se tratan con fungicida (benomil 1 g/L) y se siembran en semilleros con sustrato esterilizado (arena + compost 1:1). Después de 45-60 días, los brotes están listos para transplante. Se recomienda usar esta técnica solo con material certificado libre de nematodos y picudos. El rendimiento por cormo segmentado es 70-80% de brotes viables. Esta técnica es especialmente útil para la rápida multiplicación de variedades promisorias como FHIA-20 o FHIA-21.', labels: ['plátano', 'cultivos'] },
  { title: 'Control de trips (Frankliniella parvula) en la floración del plátano', body: 'Los trips causan daños en la epidermis de los dedos del plátano, generando manchas rojizas y rugosidades que deprecian la fruta para exportación. El monitoreo se realiza revisando las brácteas de la inflorescencia en busca de adultos (1 mm, color marrón). El manejo integrado incluye: (1) embolse de la bellota con bolsas de polietileno perforadas inmediatamente después de la emergencia de la inflorescencia, (2) aplicación de insecticida (spinosad 0.3 mL/L o imidacloprid 0.5 mL/L) dentro de la bolsa al momento del embolse, (3) aplicación de aceite agrícola (1%) para control de poblaciones, (4) eliminación de brácteas no funcionales durante el desbellote, (5) conservación de enemigos naturales como Orius insidiosus.', labels: ['plátano', 'plagas', 'cultivos'] },
  { title: 'Deshije y manejo de la unidad productiva del plátano', body: 'El manejo adecuado de los hijuelos determina la productividad del plátano. Se recomienda mantener una unidad productiva con: planta madre (producción actual), hijo (próxima producción) y nieto (producción futura). Los hijuelos excedentes deben eliminarse cada 2-3 meses, seleccionando los mejor ubicados y más vigorosos (hijuelos tipo espada de 1.2-1.5 m de altura). La densidad de siembra óptima es de 1500-2000 plantas/ha para plátano hartón, y 2000-2500 plantas/ha para plátano dominico. La producción por racimo varía entre 15-25 kg para hartón y 10-15 kg para dominico. El ciclo de producción hasta cosecha es de 10-14 meses dependiendo de la altitud.', labels: ['plátano', 'cultivos'] },
  { title: 'Control del virus del mosaico del plátano (CMV) en cultivos', body: 'El virus del mosaico del pepino (Cucumber mosaic virus) en plátano se transmite por áfidos en forma no persistente. Los síntomas incluyen mosaico clorótico en hojas jóvenes, deformación de láminas foliares y enanismo de la planta. El manejo preventivo incluye: (1) uso de colinos certificados libres de virus, (2) control de poblaciones de áfidos vectores con aplicaciones de aceite agrícola (1%) + jabón potásico (0.5%), (3) eliminación de plantas con síntomas (roguing) en las primeras 8 semanas después de siembra, (4) siembra de barreras vivas con maíz alrededor del lote para interceptar áfidos, (5) evitar el uso de herramientas contaminadas. No existe control químico curativo para la enfermedad; la prevención es la única estrategia viable.', labels: ['plátano', 'plagas', 'cultivos'] },

  // ── Plátano: Suelos y Nutrición ──
  { title: 'Requerimientos de drenaje y manejo del suelo para plátano', body: 'El plátano es extremadamente sensible al encharcamiento. El nivel freático debe mantenerse a más de 60 cm de profundidad para evitar asfixia radical. En suelos arcillosos se recomienda construir camas elevadas (30-40 cm de alto) con surcos de drenaje cada 6-8 m. Los suelos óptimos para plátano son los francos a franco-arcillosos (texturas: FA, FAr, FArL), profundos (>80 cm), con pH entre 5.5-6.5 y contenido de materia orgánica superior al 3%. En suelos de textura arenosa se requieren riegos frecuentes (cada 3-4 días en época seca) con una lámina de 15-20 mm/riego. La aplicación de mulch orgánico (hojas secas, residuos de cosecha) alrededor de la planta reduce la evaporación y aporta materia orgánica.', labels: ['plátano', 'suelos', 'cultivos'] },
  { title: 'Corrección de deficiencias nutricionales en plátano: identificación visual', body: 'La identificación temprana de deficiencias nutricionales permite corregirlas antes de que afecten la producción. Deficiencia de nitrógeno: hojas verde pálido a amarillo uniforme, crecimiento lento. Fósforo: hojas verde oscuro con necrosis en bordes de hojas viejas, crecimiento radicular reducido. Potasio: clorosis marginal en hojas viejas que progresa a necrosis, racimos pequeños. Magnesio: clorosis intervenal en forma de V invertida desde el borde hacia la nervadura central. Zinc: hojas nuevas pequeñas y estrechas (roseta), bandas cloróticas. Boro: deformación de hojas nuevas, racimos con dedos mal formados. La corrección se realiza mediante fertilización foliar con quelatos (Zn-EDTA 0.5 g/L, B 0.3 g/L) en aplicaciones cada 15 días hasta recuperación.', labels: ['plátano', 'nutrición', 'cultivos'] },

  // ── Lulo: Cultivo ──
  { title: 'Establecimiento del cultivo de lulo (Solanum quitoense) en condiciones de ladera', body: 'El lulo es un cultivo promisorio de la región andina colombiana, adaptado a altitudes entre 1500-2200 m. La preparación del terreno en laderas debe hacerse con curvas a nivel y acequias de ladera para controlar la erosión. El marco de siembra recomendado es 2x2 m (2500 plantas/ha) en sistema tresbolillo. Los hoyos (40x40x40 cm) requieren 5 kg de materia orgánica compostada, 150 g de cal dolomítica y 100 g de DAP. Las variedades recomendadas son: lulo común (Solanum quitoense var. septentrionale) y lulo la selva (variedad mejorada con tolerancia a nematodos). El tutorado es indispensable a partir de los 6 meses usando postes de madera (2 m de altura) y alambre galvanizado para sostener las ramas productivas.', labels: ['lulo', 'cultivos'] },
  { title: 'Manejo del pasador del fruto del lulo (Neoleucinodes elegantalis)', body: 'El pasador del fruto (Neoleucinodes elegantalis) causa pérdidas del 20-40% en frutos de lulo. La hembra oviposita en frutos verdes y las larvas penetran consumiendo la pulpa, causando pudrición y caída prematura. El manejo integrado incluye: (1) monitoreo con trampas de luz y feromonas, (2) recolección y eliminación de frutos caídos y dañados cada 8-10 días, (3) aplicación de insecticidas biológicos: Bacillus thuringiensis (1 g/L) cada 15 días en época de floración-fructificación, (4) embolse individual de frutos con bolsas de papel craft durante el desarrollo del fruto, (5) liberación de Trichogramma spp. (10 pulgadas/ha/semana) para control de huevos, (6) uso de insecticidas selectivos como spinosad (0.3 mL/L) en poblaciones altas.', labels: ['lulo', 'plagas', 'cultivos'] },
  { title: 'Fertilización del lulo: requerimientos y programa de aplicación', body: 'El lulo requiere 250-350 kg N/ha, 80-120 kg P2O5/ha y 300-400 kg K2O/ha para producciones de 15-20 ton/ha/año. El programa de fertilización se divide en 4 etapas: (1) establecimiento (0-30 días): 50 g DAP + 50 g KCl/planta, (2) crecimiento vegetativo (30-90 días): 30 g urea + 30 g KCl/planta cada 20 días, (3) floración (90-150 días): 20 g 10-20-20 + 10 g KNO3/planta cada 15 días, (4) producción (>150 días): 30 g 13-26-6 + 15 g KCl/planta cada 30 días. La fertilización orgánica con compost (5 kg/planta cada 4 meses) mejora la actividad biológica del suelo. Las aplicaciones foliares de Ca-B-Mo (1 L/ha) durante la floración reducen la caída de frutos.', labels: ['lulo', 'nutrición', 'cultivos'] },
  { title: 'Control de nematodos (Meloidogyne spp.) en cultivo de lulo', body: 'Los nematodos del nudo radical (Meloidogyne incognita, M. javanica) causan agallas en raíces de lulo, reduciendo la absorción de agua y nutrientes. Los síntomas incluyen amarillamiento generalizado, marchitez en horas cálidas y producción reducida. El manejo integrado incluye: (1) uso de portainjertos resistentes como el lulo la selva (S. quitoense x S. hirtum), (2) solarización del suelo (plástico transparente por 30-40 días en época seca), (3) aplicación de nematicidas biológicos a base de Paecilomyces lilacinus (2 kg/ha cada 3 meses), (4) incorporación de materia orgánica (20 ton/ha de compost) que estimula microbiota antagonista, (5) siembra de plantas antagonistas (Crotalaria juncea como cobertura previa), (6) rotación con cultivos no hospedantes (maíz, fríjol) por 2 años.', labels: ['lulo', 'plagas', 'cultivos', 'suelos'] },
  { title: 'Manejo del tizón tardío (Phytophthora infestans) en lulo', body: 'El tizón tardío es una enfermedad devastadora del lulo causada por Phytophthora infestans, el mismo patógeno de la papa. Los síntomas incluyen manchas acuosas irregulares en hojas con borde clorótico y esporulación blanquecina en el envés en condiciones de alta humedad. El manejo integrado requiere: (1) aplicación preventiva de fungicidas protectantes como mancozeb (2 kg/ha) o clorotalonil (2 L/ha) cada 7 días en época lluviosa, (2) alternancia con fungicidas sistémicos como metalaxil + mancozeb (2.5 kg/ha) cada 15 días, (3) poda de formación para mejorar aireación, (4) eliminación de plantas voluntarias de solanáceas cerca del lote, (5) riego por goteo para evitar mojar follaje, (6) uso de variedades tolerantes (lujo la selva). En cultivos orgánicos, el caldo bordelés (2%) cada 8 días da buen control preventivo.', labels: ['lulo', 'plagas', 'cultivos'] },
  { title: 'Poda y tutorado del lulo para maximizar producción', body: 'El lulo requiere podas regulares para mantener la productividad. La poda de formación se realiza a los 3-4 meses, seleccionando 3-4 ramas principales. La poda de mantenimiento se hace cada 2-3 meses eliminando: (1) ramas secas, enfermas o dañadas, (2) chupones del tallo principal, (3) ramas entrecruzadas, (4) ramas que tocan el suelo. El tutorado se realiza con postes de 2.5 m enterrados 40 cm, con 3 hilos de alambre (a 60, 120 y 180 cm). Las ramas se amarran al tutor con cinta de rafia conforme crecen. Una planta bien manejada produce 5-8 kg de fruta en su primer año y 10-15 kg a partir del segundo año. La vida útil del cultivo es de 2-3 años, después de los cuales se recomienda renovación completa del lote.', labels: ['lulo', 'cultivos'] },
  { title: 'Cosecha y manejo poscosecha del lulo: grados de madurez y conservación', body: 'El lulo se cosecha en el estado pintón (75-100% de coloración de la cáscara), cuando la pulpa inicia el viraje de verde a naranja. La cosecha se realiza manualmente cortando el pedúnculo con tijeras. La clasificación se hace por diámetro: primera (>7 cm), segunda (5-7 cm) y tercera (<5 cm). La fruta se conserva hasta 15-20 días a 7-10°C y 85-90% HR. La maduración completa se alcanza a los 5-7 días a temperatura ambiente (18-22°C). Los frutos maduros presentan color amarillo-anaranjado intenso, pulpa anaranjada con aroma característico y acidez titulable de 2.5-3.5% de ácido cítrico. Para pulpa congelada, el lulo debe procesarse en estado de madurez completa y congelarse a -18°C, manteniendo sus propiedades hasta 12 meses.', labels: ['lulo', 'cultivos', 'cosecha'] },
  { title: 'Control de la mosca del ovario (Dasiops spp.) en lulo', body: 'La mosca del ovario (Dasiops inedulis, D. curubae) es la principal plaga del lulo en Colombia. Las hembras ovipositan en botones florales y frutos pequeños, y las larvas se alimentan de la pulpa causando caída de flores y frutos. El monitoreo se realiza con trampas McPhail cebadas con proteína hidrolizada al 5%. El umbral de acción es 10 moscas/trampa/semana. El manejo incluye: (1) recolección semanal de frutos caídos y descomposición en bolsas selladas, (2) aplicación de cebos tóxicos compuestos por proteína hidrolizada (5%) + insecticida (Spinosad 0.2 mL/L) en parches cada 10 m, (3) liberación de parasitoides de pupas como Dirhinus giffardii, (4) embolse de frutos con bolsas de malla, (5) uso de trampas de feromonas para captura masiva.', labels: ['lulo', 'plagas', 'cultivos'] },
  { title: 'Variedades de lulo para diferentes pisos térmicos colombianos', body: 'La selección varietal del lulo depende del piso térmico. Para altitudes de 1500-1800 m se recomienda la variedad La Selva (tolerante a nematodos, alta producción 15-20 ton/ha), desarrollada por CORPOICA. Para 1800-2200 m se adapta bien el lulo común regional (buen sabor, menor productividad 10-15 ton/ha). Para altitudes superiores a 2200 m se recomienda el lulo castilla (Solanum quitoense var. quitoense), más tolerante a bajas temperaturas. Existen accesiones promisorias como el lulo agridulce (S. pseudolulo) con menor acidez y el lulo de perro (S. hirtum) usado como portainjerto resistente a nematodos. La semilla sexual debe adquirirse de fuentes certificadas con pureza varietal superior al 95% y poder germinativo mayor al 80%.', labels: ['lulo', 'cultivos'] },

  // ── Lulo: Plagas y Enfermedades ──
  { title: 'Manejo del oídio o ceniza (Oidium sp.) en lulo', body: 'El oídio en lulo se manifiesta como un polvo blanco talcoso en hojas jóvenes, brotes y flores, causando deformación y caída prematura. La enfermedad es favorecida por alta humedad relativa (>70%) y temperaturas moderadas (18-25°C). El manejo incluye: (1) aplicación de azufre micronizado (3 g/L) cada 10-15 días como preventivo, (2) fungicidas sistémicos como triadimefon (0.5 g/L) o tebuconazol (1 mL/L) al detectar los primeros síntomas, (3) biofungicidas a base de Bacillus subtilis (2 mL/L) como alternativa orgánica, (4) poda de ventilación para reducir humedad dentro del dosel, (5) evitar excesos de fertilización nitrogenada que favorecen crecimiento suculento susceptible. La rotación de ingredientes activos es clave para evitar resistencia del patógeno.', labels: ['lulo', 'plagas', 'cultivos'] },
  { title: 'Sistema de riego por goteo para lulo: diseño y manejo', body: 'El riego por goteo optimiza el uso del agua en lulo, especialmente en laderas. El diseño requiere: goteros autocompensantes de 2-4 L/h separados cada 30-40 cm, con dos líneas de goteo por hilera de plantas. La frecuencia de riego en época seca es cada 2-3 días con una lámina de 8-12 mm/riego. El consumo hídrico máximo del lulo es 4-5 mm/día. El uso de mulching plástico (plástico negro calibre 1.5) sobre las camas reduce la evaporación en un 30% y controla arvenses. El análisis de la calidad del agua debe verificar: pH 5.5-7.0, CE <1.5 dS/m, contenido de Na <40%. El fertirriego permite aplicar dosis fraccionadas de fertilizantes solubles, mejorando la eficiencia de uso de nutrientes hasta en un 40%.', labels: ['lulo', 'riego', 'cultivos'] },

  // ── Plagas Generales y Soluciones ──
  { title: 'Control biológico de áfidos (Aphis gossypii) en cultivos agrícolas', body: 'Los áfidos o pulgones causan daños directos (succión de savia) e indirectos (transmisión de virus) en múltiples cultivos. El control biológico mediante la liberación de Chrysoperla carnea (crisopa) a razón de 5000 huevos/ha cada 8-15 días muestra eficacias superiores al 80%. Las larvas de crisopa consumen 200-300 áfidos/día durante su desarrollo. Alternativamente, las mariquitas (Hippodamia convergens) liberadas a 2000 adultos/ha controlan infestaciones moderadas. Para el control preventivo se recomienda: (1) aplicación de jabón potásico (2%) cada 8-10 días, (2) aceite de neem (0.5%) como regulador de crecimiento, (3) conservación de franjas florales que albergan enemigos naturales, (4) evitar insecticidas de amplio espectro durante los primeros 30 días del cultivo para no eliminar la fauna benéfica.', labels: ['plagas', 'cultivos'] },
  { title: 'Manejo integrado de trips (Frankliniella occidentalis) en invernadero', body: 'Los trips son plagas polífagas que afectan hortalizas y frutales, causando daños directos por raspado de tejidos y transmisión del virus del bronceado del tomate (TSWV). El manejo integrado incluye: (1) mallas anti-insectos (50 mesh) en ventilaciones del invernadero, (2) trampas azules pegajosas a razón de 20-30/ha para monitoreo y captura masiva, (3) aplicación de depredadores como Amblyseius swirskii (50-100 ácaros/m²) y Orius laevigatus (2-5 chinches/m²), (4) aplicación de hongo entomopatógeno Beauveria bassiana al suelo para controlar pupas, (5) insecticidas biorracionales como Spinosad (0.3 mL/L) y Abamectina (0.5 mL/L) en rotación. La temperatura bajo invernadero debe manejarse para no favorecer el desarrollo del trips (<30°C).', labels: ['plagas', 'cultivos'] },
  { title: 'Control de cochinillas harinosas (Planococcus citri) en frutales', body: 'La cochinilla harinosa es una plaga frecuente en cítricos, cacao y café, causando debilitamiento por succión de savia y favoreciendo el desarrollo de fumagina. El control biológico con Cryptolaemus montrouzieri (mariquita australiana) es altamente efectivo: se liberan 10-20 adultos/árbol infestado. Las larvas de Cryptolaemus consumen hasta 250 cochinillas durante su desarrollo. Complementariamente se aplican: (1) aceite mineral al 1% para asfixiar cochinillas, (2) jabón potásico (2%) cada 8 días, (3) hongos entomopatógenos Lecanicillium lecanii (10^12 conidias/ha) en condiciones de alta humedad, (4) control de hormigas que las protegen usando cebos en la base del árbol. El monitoreo debe incluir revisión de nudos, axilas de ramas y frutos.', labels: ['plagas', 'frutales', 'cultivos'] },
  { title: 'Manejo de mosca blanca (Trialeurodes vaporariorum) en hortalizas', body: 'La mosca blanca es plaga clave en tomate, fríjol y hortalizas, causando daños directos (succión de savia) e indirectos (transmisión de geminivirus, fumagina). El manejo integrado se basa en: (1) barreras vivas con maíz alrededor del lote (cortina vegetal), (2) trampas amarillas pegajosas (50/ha) para monitoreo y captura masiva, (3) aplicación de Encarsia formosa (avispita parasitoide) a razón de 5 adultos/m²/semana durante 4-6 semanas, (4) aplicación de Beauveria bassiana (10^12 conidias/ha) + aceite agrícola (0.5%) en horas de alta humedad, (5) insecticidas reguladores de crecimiento como buprofezin (1 mL/L) sobre ninfas, (6) eliminación de malezas hospedantes y residuos de cosecha. La rotación de cultivos con poáceas (maíz, sorgo) reduce la presión de la plaga.', labels: ['plagas', 'cultivos'] },
  { title: 'Fertilización orgánica: preparación de compost de alta calidad', body: 'El compost de alta calidad requiere una relación C/N inicial de 25-30:1, lograda mezclando 3 partes de material rico en carbono (residuos de cosecha, hojas secas, cascarilla de arroz) por 1 parte de material rico en nitrógeno (gallinaza, estiércol bovino, torga de café). La pila debe tener al menos 1.5 m de alto por 2-3 m de ancho, con humedad del 50-60% (prueba del puño: al apretar, debe gotear 1-2 gotas de agua). Los volteos se realizan cada 7-14 días durante los primeros 2 meses, luego cada 30 días. La temperatura del centro debe alcanzar 55-65°C durante la fase termofílica (primeros 15-20 días) para eliminar patógenos y semillas de malezas. El compost maduro (3-5 meses) presenta color marrón oscuro, olor a tierra húmeda y relación C/N final <15:1.', labels: ['nutrición', 'suelos', 'cultivos'] },
  { title: 'Control de gusanos cortadores (Agrotis ipsilon) en semilleros', body: 'Los gusanos cortadores atacan plántulas recién transplantadas cortando el tallo a nivel del suelo en horas nocturnas. El monitoreo se realiza revisando la base de las plantas al amanecer y usando trampas de caída (pitfall traps) con melaza. El manejo integrado para semilleros incluye: (1) aplicar cebos tóxicos compuestos de salvado de trigo (10 kg) + melaza (1 kg) + insecticida (Spinosad 200 mL) + agua (5 L), distribuidos al atardecer alrededor del semillero, (2) colocar collares protectores de cartón o botellas plásticas cortadas alrededor de cada plántula, (3) mantener el semillero libre de arvenses 15 días antes del transplante, (4) aplicación de nematodos entomopatógenos Steinernema feltiae (10^9 IJ/ha) al suelo, (5) Baccillus thuringiensis kurstaki (1 g/L) aplicado al suelo en infestaciones altas.', labels: ['plagas', 'cultivos'] },
  { title: 'Manejo sostenible de arvenses en sistemas agroecológicos', body: 'El manejo ecológico de arvenses se basa en la prevención y el control cultural. Las estrategias incluyen: (1) coberturas vegetales nobles (Arachis pintoi, Pueraria phaseoloides, Desmodium ovalifolium) que compiten con arvenses agresivas, (2) mulch de residuos de cosecha (5-10 ton/ha) que suprime la germinación de semillas de malezas, (3) rotación de cultivos para evitar la especialización de arvenses, (4) control manual selectivo eliminando solo especies problema (coquito, pasto estrella, guarda rocío), (5) cultivos de cobertura en épocas de barbecho como avena forrajera o vicia, (6) uso de desbrozadora mecánica en calles. Se desaconseja herbecidas químicos por su impacto en la microbiota, la salud humana y la contaminación de fuentes hídricas.', labels: ['suelos', 'cultivos'] },
  { title: 'Biodigestores: producción de biol y biogas a partir de residuos agrícolas', body: 'Los biodigestores de tipo tubular de bajo costo procesan estiércol bovino (30 kg/día para una familia de 5 personas) produciendo biogas para cocción y biol como fertilizante foliar. La relación de carga óptima es 1 parte de estiércol por 3 partes de agua, con un tiempo de retención de 30-40 días en clima cálido y 60-70 días en clima frío. El biol producido contiene nutrientes (N 0.5-1.5%, P 0.1-0.3%, K 0.3-0.8%) más fitohormonas y aminoácidos que estimulan el crecimiento vegetal. Se aplica diluido al 10-20% en agua cada 15 días como fertilizante foliar. Un biodigestor de 6 m³ procesa el estiércol de 3-4 bovinos y produce suficiente biogas para cocinar 3-4 horas/día, reduciendo la presión sobre los bosques para leña.', labels: ['suelos', 'cultivos'] },
  { title: 'Calibración de equipos de fumigación para aplicación eficiente de agroquímicos', body: 'La calibración correcta de equipos de fumigación evita pérdidas de producto y contaminación. Para bomba de espalda manual: (1) llenar el tanque con agua limpia, (2) seleccionar la boquilla adecuada (abanico para herbicidas, cono para fungicidas), (3) marcar un área de 100 m², (4) fumigar a paso constante registrando el tiempo y el volumen gastado, (5) calcular: caudal (L/min) = volumen gastado / tiempo. La dosis correcta se calcula como: producto (mL o g) = (dosis recomendada por ha × volumen del tanque) / volumen de aplicación por ha. La velocidad de aplicación óptima para fungicidas en cultivos de porte bajo es 250-300 L/ha. Se recomienda usar agua con pH entre 5.5-6.5 para evitar degradación del producto, ajustando con ácido cítrico (1-2 g/100 L) si es necesario.', labels: ['cultivos'] },
  { title: 'Control de la antracnosis (Colletotrichum spp.) en frutales tropicales', body: 'La antracnosis afecta frutales como mango, aguacate, papaya y cítricos, causando manchas necróticas hundidas en frutos y defoliación en ramas. El manejo integrado se basa en: (1) poda de ramas afectadas y eliminación de frutos momificados del árbol y del suelo, (2) aplicación de fungicidas protectantes: mancozeb (2 kg/ha) o clorotalonil (2 L/ha) cada 7-10 días en época de floración y desarrollo de frutos, (3) alternancia con fungicidas sistémicos: azoxistrobina (0.5 L/ha) o pyraclostrobina (0.3 L/ha) en períodos críticos, (4) aplicación poscosecha: inmersión de frutos en agua caliente (52°C por 5 min) o fungicida (tiabendazol 1 mL/L), (5) manejo nutricional balanceado (evitar exceso de N) y (6) uso de silicato de potasio (2 L/ha) que fortalece la cutícula de frutos y hojas.', labels: ['plagas', 'frutales', 'cultivos'] },
  { title: 'Implementación de sistemas de captación de agua lluvia para riego', body: 'Los sistemas de captación de agua lluvia son esenciales para la agricultura familiar en zonas de ladera con déficit hídrico estacional. El diseño básico incluye: (1) área de captación (techo de vivienda o invernadero), (2) canaletas de PVC de 4" con rejilla para hojas, (3) tanque de almacenamiento (10000-20000 L para 2000 m² de cultivo), (4) filtro de sólidos (malla de 1 mm), (5) sistema de distribución por gravedad o bombeo. La precipitación mínima requerida es 600 mm/año, con un área de captación de 100 m² por cada 10000 L de capacidad de almacenamiento. El agua captada debe protegerse de la luz solar para evitar proliferación de algas, agregando 5 mL de hipoclorito de sodio al 5% por cada 1000 L de almacenamiento. El sistema puede complementarse con bombas manuales tipo ariete para elevar agua a tanques de distribución.', labels: ['riego', 'cultivos'] },
  { title: 'Producción de abonos verdes: leguminosas como fuente de nitrógeno', body: 'Los abonos verdes son cultivos que se incorporan al suelo para mejorar su fertilidad. Las leguminosas como Crotalaria juncea, Vigna unguiculada (caupí), Mucuna pruriens (frijol terciopelo) y Canavalia ensiformis (canavalia) pueden fijar 80-200 kg N/ha cuando se incorporan al inicio de floración (45-60 días después de siembra). La biomasa producida oscila entre 15-30 ton/ha de materia verde. Se recomienda sembrar en rotación con cultivos exigentes en nitrógeno (maíz, tomate, brócoli) o en relevo (intercalado) durante el período de barbecho. La incorporación debe hacerse 15-20 días antes de la siembra del cultivo principal para permitir la descomposición inicial. El sistema mejora la estructura del suelo, la retención de humedad y la actividad biológica.', labels: ['suelos', 'nutrición', 'cultivos'] },
  { title: 'Control de la arruinadora del cacao (Carmenta foraseminis)', body: 'La arruinadora del cacao (Carmenta foraseminis) es un lepidóptero cuyas larvas perforan la mazorca desde la base del pedúnculo, causando pudrición interna sin daños externos visibles inicialmente. El monitoreo requiere revisión periódica de mazorcas buscando pequeños orificios en la base y excremento larval. El manejo integrado incluye: (1) eliminación y destrucción de mazorcas infestadas cada 15 días, (2) aplicación de insecticidas biológicos: Bacillus thuringiensis kurstaki (1 g/L) dirigido a mazorcas pequeñas (<8 cm), (3) control cultural mediante podas de copa que permitan entrada de luz y reduzcan humedad, (4) aplicación de hongos entomopatógenos Metarhizium anisopliae (10^13 conidias/ha) al suelo alrededor del árbol para controlar pupas, (5) liberación de Trichogramma pretiosum (10 pulgadas/ha/semana) para parasitación de huevos.', labels: ['cacao', 'plagas', 'cultivos'] },
  { title: 'Manejo poscosecha de frutas tropicales: cadena de frío y vida útil', body: 'La cadena de frío es el factor más crítico para la conservación de frutas tropicales después de la cosecha. El protocolo general incluye: (1) precooling o enfriamiento rápido en las primeras 4-6 horas poscosecha para eliminar el calor de campo (usando hidroenfriamiento o aire forzado), (2) almacenamiento a temperatura óptima: banano 13-14°C, aguacate 5-7°C, mango 10-13°C, papaya 10-12°C, (3) humedad relativa de 85-95% para evitar pérdida de peso por deshidratación, (4) atmósferas modificadas con 2-5% O2 y 3-8% CO2 para reducir respiración y producción de etileno, (5) control de etileno con permanganato de potasio en filtros. La implementación correcta de la cadena de frío puede extender la vida útil de 3-10 días a 3-8 semanas según la fruta.', labels: ['cosecha', 'cultivos'] },
  { title: 'Lombricultura: producción de humus a partir de residuos orgánicos', body: 'La lombricultura transforma residuos orgánicos en humus de alta calidad usando Eisenia fetida (lombriz roja californiana). Cada lombriz consume su peso en residuos diariamente (0.5-1 g/día), produciendo humus equivalente al 60-70% de lo consumido. El lecho ideal incluye: 70% estiércol de bovino precomposteado (15-20 días) y 30% residuos vegetales picados. La densidad de siembra óptima es 20000-30000 lombrices/m³. La humedad del lecho debe mantenerse al 70-80% y la temperatura entre 18-25°C. La cosecha del humus se realiza cada 3-4 meses mediante el método de volteo y separación. El humus de lombriz contiene: N 1.5-2.5%, P 0.5-1.5%, K 0.8-1.5%, Ca 2-4%, Mg 0.3-0.8%, 50-70% de materia orgánica y carga microbiana de 10^8-10^9 UFC/g.', labels: ['suelos', 'nutrición', 'cultivos'] },
  { title: 'Control de babosas y caracoles (Moluscos) en huertos orgánicos', body: 'Los moluscos causan daños nocturnos en plántulas, hojas y frutos cerca del suelo en condiciones de alta humedad. El manejo orgánico incluye: (1) barreras físicas con ceniza de madera o cáscara de huevo triturada alrededor de las plantas, (2) trampas de cerveza (recipientes enterrados a nivel del suelo con cerveza, renovada cada 3 días), (3) depredadores naturales: gallinas (5-10/ha) en horas del día, sapos y ranas, (4) aplicación de nematodos Phasmarhabditis hermaphrodita (10^6 IJ/m²) al suelo húmedo en horas de la tarde, (5) cebos orgánicos a base de salvado + melaza, (6) eliminación de refugios (tablas, piedras, maleza densa) donde se ocultan durante el día. Los molusquicidas químicos a base de metaldehído deben evitarse por su toxicidad en fauna doméstica.', labels: ['plagas', 'cultivos'] },
  { title: 'Propagación vegetativa de frutales: estaquillado y acodo aéreo', body: 'La propagación vegetativa permite multiplicar clones seleccionados manteniendo las características de la planta madre. El estaquillado funciona bien en especies como vid, higuera y olivo: se toman estacas de 20-25 cm de ramas semileñosas de 1 año, con 3-4 yemas. Se tratan con ácido indol-butírico (AIB) al 2000 ppm y se colocan en sustrato húmedo (arena-perlita 1:1) bajo nebulización. El acodo aéreo es ideal para frutales tropicales: se selecciona una rama de 1-2 cm de diámetro, se anilla (corteza removida 2-3 cm), se cubre con sustrato húmedo envuelto en plástico. Después de 30-60 días (según la especie), se forman raíces visibles a través del plástico y se separa de la planta madre. El prendimiento (80-90%) del acodo es superior al estaquillado para la mayoría de especies tropicales.', labels: ['cultivos'] },
  { title: 'Indicadores biológicos de la calidad del suelo agrícola', body: 'La calidad del suelo se evalúa mediante indicadores biológicos sensibles al manejo. La respiración basal del suelo (CO2 liberado en 24h) indica actividad microbiana: valores óptimos >30 mg CO2/kg suelo/día. La biomasa microbiana (C-microbiano) debe representar 2-5% del carbono orgánico total. La relación hongos/bacterias ideal es 0.5-1.0 en suelos agrícolas, siendo mayor (>1.5) en suelos conservados. La actividad enzimática (fosfatasa alcalina, β-glucosidasa, deshidrogenasa) indica ciclaje de nutrientes. La presencia de lombrices (10-20/m² en suelo agrícola) y colémbolos (>1000/m²) son indicadores de buena estructura y bajo impacto por labranza. Mineralización de nitrógeno potencial >20 mg N/kg/28 días indica buena fertilidad. Estos análisis complementan los análisis químicos convencionales.', labels: ['suelos', 'cultivos'] },
  { title: 'Erosión del suelo en laderas y cultivos de ladera', body: 'La erosión hídrica en laderas cultivadas supera 100 ton/ha/año en sistemas sin manejo conservacionista. Las estrategias de control son: (1) siembra en curvas a nivel con trazado mediante nivel A, (2) barreras vivas de Vetiver (Chrysopogon zizanioides) cada 6-10 m, (3) acequias de ladera (zanjas de infiltración) a cada 8-15 m según pendiente, (4) cobertura permanente del suelo con residuos de cosecha (3-5 ton/ha), (5) sistema agroforestal con árboles en contorno cada 10 m (6) cultivos en fajas alternando gramíneas y leguminosas. La pérdida de suelo tolerable es 10-12 ton/ha/año, equivalente a 1 mm de suelo perdido. Un milímetro de suelo tarda 100-400 años en formarse naturalmente, lo que hace crítica la conservación del recurso.', labels: ['suelos', 'cultivos'] },
  { title: 'Agroecología: principios para la transición de fincas convencionales', body: 'La transición agroecológica requiere un proceso gradual de 3-5 años. Los principios clave son: (1) diversificación temporal y espacial (policultivos, rotaciones, sistemas agroforestales), (2) reciclaje de nutrientes dentro de la finca (compost, abonos verdes, estiércoles), (3) manejo ecológico de plagas (conservación de enemigos naturales, control biológico, variedades resistentes), (4) salud del suelo como prioridad (labranza mínima, coberturas, materia orgánica), (5) integración animal (bovinos, aves, cerdos) que aportan estiércol y diversifican ingresos. El plan de transición incluye: eliminar progresivamente agroquímicos, establecer cercas vivas y corredores biológicos, implementar sistemas de captación de agua. La certificación orgánica (Resolución 187/2006 ICA Colombia) requiere 2 años de manejo limpio.', labels: ['cultivos', 'suelos'] },

  // ── Café: Plagas adicionales ──
  { title: 'Control del minador de la hoja del café (Leucoptera coffeella)', body: 'El minador de la hoja del café forma galerías serpentiformes en el haz de las hojas, reduciendo el área fotosintética y causando defoliación severa en ataques intensos. La plaga es más severa en cafetales a plena exposición solar y en épocas secas. El monitoreo se realiza contando hojas minadas en 20 árboles/lote (umbral: 30% de hojas con minas activas). El manejo integrado incluye: (1) regulación de sombrío (mínimo 30%) que reduce la incidencia, (2) control biológico con avispas parasitoides Orgilus spp. y Closterocerus spp., (3) aplicación de insecticida biológico Bacillus thuringiensis (1 g/L) cuando se detecten larvas pequeñas, (4) en infestaciones severas, insecticidas selectivos como clorantraniliprol (0.3 mL/L) o spinosad (0.4 mL/L), (5) mantener la fertilización balanceada para que el café tolere mejor el daño.', labels: ['café', 'plagas', 'cultivos'] },
  { title: 'Cafés especiales: perfil de taza y procesamiento diferenciado', body: 'Los cafés especiales se definen por su puntaje en catación (SCA ≥80 puntos) y su trazabilidad desde el origen. Los perfiles de taza dependen del procesamiento: (1) lavado tradicional: taza limpia, acidez brillante, cuerpo medio, notas frutales y florales, (2) honey: cuerpo más denso, dulzor pronunciado, acidez moderada, notas a caramelo y miel, (3) natural: cuerpo completo, dulzor intenso, notas a frutas rojas y fermentadas, baja acidez. El procesamiento honey requiere despulpar sin lavar y secar con el mucílago adherido (15-20 días en camas africanas). El natural requiere selección rigurosa de frutos maduros (flotación y densidad) y secado lento (20-30 días) para evitar fermentaciones indeseables. La altitud óptima para cafés especiales colombianos es 1600-2100 m.', labels: ['café', 'cultivos', 'cosecha'] },
  { title: 'Manejo de la mancha de hierro (Cercospora coffeicola) en café', body: 'La mancha de hierro (Cercospora coffeicola) en café se presenta como manchas circulares de 3-8 mm con centro gris claro y borde púrpura en hojas maduras y viejas. La enfermedad es más severa en condiciones de estrés nutricional (deficiencia de K, exceso de N) y en zonas de baja altitud. Para su manejo se recomienda: (1) fertilización balanceada con énfasis en potasio (350-450 kg K2O/ha/año), (2) aplicaciones dirigidas de fungicidas cúpricos (oxicloruro de cobre 3 g/L) o triazoles (propiconazol 0.5 L/ha) al inicio de las lluvias, (3) poda de ramas bajas y mejora de la aireación, (4) mantenimiento de coberturas nobles para reducir el impacto de gotas de lluvia. En cafetales con sombrío denso (>50%), se debe regular para mejorar la circulación de aire y reducir la humedad foliar.', labels: ['café', 'plagas', 'cultivos'] },

  // ── Suelos: más cobertura ──
  { title: 'Manejo ecológico de la fertilidad del suelo con microorganismos', body: 'Los microorganismos benéficos del suelo (bacterias fijadoras de N, hongos micorrícicos, bacterias solubilizadoras de P) pueden potenciarse mediante la aplicación de microorganismos eficientes (EM). La preparación artesanal de EM se hace fermentando: 10 L de suero de leche, 1 L de melaza, 100 g de levadura, 100 g de cal agrícola en 100 L de agua, por 7-10 días sin exposición al sol. Se aplica diluido al 5% en el suelo cada 30-45 días. Los hongos micorrícicos arbusculares (Glomus spp., Acaulospora spp.) mejoran la absorción de P y agua: se aplican 10 kg/ha de inóculo en la siembra. Las bacterias rizosféricas (Azospirillum, Azotobacter, Pseudomonas) fijan nitrógeno y producen fitohormonas: se aplican como biofertilizante líquido (5 L/ha) cada 2 meses. La combinación de EM + micorrizas + bacterias puede reducir la fertilización química en un 30-50%.', labels: ['suelos', 'nutrición', 'cultivos'] },
  { title: 'Control de arácnidos rojos (Tetranychus urticae) en cultivos protegidos', body: 'La araña roja (Tetranychus urticae) es una plaga frecuente en invernaderos y cultivos protegidos, causando punteaduras cloróticas en hojas, debilitamiento general y pérdida de producción. El control biológico es la estrategia más efectiva: (1) liberación del ácaro depredador Phytoseiulus persimilis a razón de 10-20 adultos/m² cuando se detecten los primeros focos, (2) aplicación de Neoseiulus californicus como complemento en condiciones de baja humedad relativa, (3) depredadores adicionales: Amblyseius swirskii y Stethorus punctillum. El control químico selectivo incluye acaricidas como abamectina (0.5 mL/L) o aceite de neem (0.5%). Las condiciones favorables para la plaga son temperatura >30°C y humedad <50%; por tanto, el manejo climático (ventilación, nebulización) es clave.', labels: ['plagas', 'cultivos'] },
  { title: 'Producción de semilla certificada de papa para siembra', body: 'La semilla certificada de papa es fundamental para garantizar sanidad y productividad del cultivo. Las categorías de semilla en Colombia son: Básica Temprana (BT), Básica Tardía (BTa), Registrada (R) y Certificada (C). La semilla certificada debe tener pureza varietal >99%, libre de virus PVY, PVX, PLRV (tolerancia <1%) y libre de bacteriosis (Ralstonia solanacearum, Clavibacter michiganensis). El tamaño óptimo del tubérculo-semilla es 40-60 mm (categoría II) con peso de 50-80 g. La densidad de siembra recomendada para semilla certificada es 2000-2500 kg/ha con distancias de 0.8-1.0 m entre surcos y 0.25-0.30 m entre plantas. El almacenamiento debe hacerse a 4-6°C, HR 85-90%, en cuartos oscuros con ventilación y control de etileno.', labels: ['cultivos'] },
  { title: 'Control de la gota de la papa (Phytophthora infestans) con fungicidas', body: 'La gota de la papa causada por Phytophthora infestans requiere un programa de aspersiones calendarizadas en zonas de alta presión de la enfermedad (>1000 mm/año). El programa preventivo se inicia cuando las plantas alcanzan 15-20 cm de altura. La rotación de fungicidas incluye: protectantes (mancozeb 2 kg/ha, clorotalonil 2 L/ha) aplicados cada 5-7 días en época lluviosa, y sistémicos (metalaxil + mancozeb 2.5 kg/ha, dimetomorf 0.5 L/ha, cimoxanilo + mancozeb 2 kg/ha) cada 10-14 días. El monitoreo climático usando la regla de los 7 días (temperatura 10-20°C + HR >80% + lluvia >2 mm) permite anticipar períodos de alto riesgo. En lotes con historial severo, se recomienda usar variedades resistentes como Pastusa Suprema, Diacol Capiro o Parda Pastusa.', labels: ['plagas', 'cultivos'] },
  { title: 'Sistemas de información geográfica (SIG) aplicados a la agricultura de precisión', body: 'Los SIG permiten mapear la variabilidad espacial del suelo y los cultivos para optimizar el manejo agronómico. Los mapas de rendimiento (generados con monitores de cosecha) se correlacionan con mapas de propiedades del suelo (pH, CIC, MO, nutrientes) para crear zonas de manejo homogéneas. El muestreo de suelos dirigido por zonas de manejo reduce el número de muestras necesarias en un 50% manteniendo la representatividad. Los índices de vegetación (NDVI, EVI) derivados de imágenes satelitales (Sentinel-2, resolución 10 m cada 5 días) permiten detectar estrés hídrico o nutricional antes de que sea visible al ojo humano. La aplicación de insumos con dosis variable (VRT) basada en mapas SIG puede aumentar la eficiencia de fertilizantes en 15-30% y reducir el impacto ambiental. Herramientas gratuitas como QGIS y Google Earth Engine facilitan la adopción de estas tecnologías.', labels: ['cultivos', 'suelos'] },

  // ── Nutrición vegetal ──
  { title: 'Diagnóstico de deficiencias de micronutrientes en cultivos tropicales', body: 'Las deficiencias de micronutrientes son frecuentes en suelos tropicales ácidos y lixiviados. Zinc (Zn): hojas pequeñas entrenudos cortos y clorosis intervenal —aplicar Zn-EDTA (0.5 g/L) foliar cada 15 días. Boro (B): deformación de hojas jóvenes, frutos con malformación, necrosis del punto de crecimiento —aplicar ácido bórico (1-2 kg/ha) al suelo o B-etanolamina (0.3 g/L) foliar en floración. Hierro (Fe): clorosis intervenal en hojas jóvenes con venas verdes (caliza activa) —aplicar Fe- quelato (0.5 g/L) foliar. Manganeso (Mn): clorosis intervenal similar a Fe pero difusa —aplicar MnSO4 (2-3 kg/ha) al suelo. Molibdeno (Mo): hojas amarillas pálidas, enrollamiento hacia arriba —aplicar molibdato de amonio (0.2 kg/ha) al suelo o foliar. La aplicación combinada de micronutrientes en fertirriego es más eficiente que las aplicaciones al suelo.', labels: ['nutrición', 'cultivos'] },
  { title: 'Agricultura regenerativa: secuestro de carbono en suelos agrícolas', body: 'La agricultura regenerativa busca recuperar la salud del suelo mientras secuestra carbono atmosférico. Las prácticas clave son: (1) labranza cero o mínima (reduce pérdida de CO2 del suelo en 1-2 ton C/ha/año), (2) cultivos de cobertura en rotación (aportan 3-10 ton biomasa/ha/año), (3) integración de sistemas silvopastoriles con árboles que almacenan carbono en biomasa y suelo, (4) manejo holístico del pastoreo con alta densidad y corta duración, (5) aplicación de compost y biochar (carbón vegetal pirolizado que permanece siglos en el suelo). El potencial de secuestro es 0.5-2 ton C/ha/año. Colombia tiene el compromiso de reducir emisiones en 51% al 2030 y la agricultura regenerativa es una herramienta clave. Los suelos saludables con 3-6% de materia orgánica almacenan 50-120 ton C/ha en los primeros 30 cm.', labels: ['suelos', 'cultivos'] },
  { title: 'Control biológico de Fusarium oxysporum en cultivos de clavel', body: 'Fusarium oxysporum f. sp. dianthi causa marchitez vascular en clavel, enfermedad de difícil control por su persistencia en el suelo (>10 años). El manejo integrado se basa en: (1) solarización del suelo (plástico transparente por 45 días en época seca, alcanzando 45-55°C a 20 cm de profundidad), (2) biofumigación con Brassica juncea (mostaza) incorporada 30 días antes de siembra, (3) aplicación de Trichoderma harzianum (10^6 UFC/g de sustrato) en el momento de siembra, (4) uso de portainjertos resistentes como la variedad Walters, (5) desinfección de herramientas de corte (hipoclorito de sodio al 2% cada corte), (6) manejo del pH del sustrato entre 6.0-6.5 y evitando exceso de NH4+ que favorece la enfermedad. En camas con altos niveles de inóculo, se recomienda el uso de sustratos inertes (perlita-arena) en bancas elevadas.', labels: ['plagas', 'cultivos'] },
  { title: 'Buenas prácticas agrícolas (BPA) para la certificación GlobalGAP', body: 'La certificación GlobalGAP es el estándar internacional más reconocido para BPA. Los requisitos incluyen: (1) registro detallado de todas las labores (siembra, fertilización, aplicación de plaguicidas, cosecha), (2) gestión de riesgos: análisis de peligros y puntos críticos de control (HACCP), (3) manejo integrado de plagas con énfasis en control biológico, (4) fertilización basada en análisis de suelos y foliares, (5) trazabilidad desde la siembra hasta el punto de venta, con códigos de lote, (6) calibración anual de equipos de aplicación, (7) capacitación del personal en manejo seguro de agroquímicos, (8) análisis de residuos de plaguicidas en producto final (<LMR), (9) gestión del recurso hídrico con análisis microbiológico del agua de riego, (10) salud ocupacional y bienestar laboral. La certificación requiere auditoría anual por ente acreditado.', labels: ['cultivos'] },
  { title: 'Control de hormigas cortadoras (Atta spp. y Acromyrmex spp.) en sistemas agrícolas', body: 'Las hormigas cortadoras son plagas significativas en sistemas agroforestales y cultivos perennes. El control integrado se basa en: (1) localización precisa de nidos mediante mapeo GPS durante la época de mayor actividad (inicio de lluvias), (2) control físico-mecánico: excavación de nidos pequeños (<2 m²) y exposición de la reina, (3) control biológico con hongos entomopatógenos Beauveria bassiana y Metarhizium anisopliae (2x10^13 conidias/ha) aplicados en el nido, (4) cebos granulados a base de sulfluramida (0.1%) en dosis de 5-10 g/nido activo, (5) barreras vivas alrededor del lote con Gliricidia sepium y Trichanthera gigantea que reducen la colonización. Se recomienda el monitoreo cada 15 días durante la época de mayor radi­cación de nuevos nidos (abril-junio).', labels: ['plagas', 'cultivos'] },
  { title: 'Manejo de la polinización dirigida en cultivos de aguacate con abejas', body: 'La polinización dirigida en aguacate (Persea americana) puede aumentar la producción entre 30-200% según la variedad. El aguacate tiene flores protogíneas dicógamas (tipo A: Hass, tipo B: Fuerte, Ettinger) que abren en momentos opuestos del día. Se recomienda colocar 4-6 colmenas/ha de Apis mellifera, distribuidas en grupos de 2 cerca de cortinas rompevientos en el lado del lote que recibe el sol de la mañana. La polinización manual complementaria con aspersión de polen (1 g de polen en 100 mL de agua + 5 g de azúcar) durante la floración principal puede aumentar el cuajado de frutos. Los factores limitantes incluyen: altas temperaturas (>32°C) que reducen la viabilidad del polen, lluvias que lavan el polen, y uso de insecticidas durante la floración. Se recomienda evitar aplicaciones de plaguicidas durante el pico de floración.', labels: ['cultivos', 'cosecha'] },
  { title: 'Secuestro de carbono en sistemas silvopastoriles intensivos (SSPI)', body: 'Los SSPI integran árboles dispersos (50-100 árboles/ha), arbustos forrajeros (Leucaena leucocephala a 1x1 m) y pastos mejorados (Brachiaria, Panicum) en rotación con periodos de ocupación cortos (12-24 h) y descanso de 30-45 días. La capacidad de carga alcanza 3-5 UGG/ha (vs 0.5-1.0 en pastoreo tradicional). El secuestro de carbono en SSPI es de 5-15 ton CO2 eq/ha/año: 80% almacenado en biomasa subterránea y materia orgánica del suelo. La leucaena fija 200-300 kg N/ha/año eliminando la necesidad de fertilizante nitrogenado. La producción de leche en SSPI alcanza 10-15 L/vaca/día frente a 4-6 L en sistemas tradicionales. Estos sistemas son priorizados en la Política Nacional de Cambio Climático (CONPES 3700) y acceden a pagos por servicios ambientales (PSA).', labels: ['suelos', 'cultivos'] },
  { title: 'Control de malezas resistentes a glifosato en cultivos transgénicos', body: 'El uso intensivo de glifosato ha seleccionado biotipos de malezas resistentes como Eleusine indica (pata de gallina), Conyza bonariensis (venadillo) y Sorghum halepense (pasto johnson). El manejo integrado de malezas resistentes (MIMAR) incluye: (1) rotación de modos de acción herbicida (ALS, ACCasa, PSII, auxinas sintéticas) en lugar de usar solo glifosato, (2) aplicaciones de herbicidas preemergentes (S-metolacloro, pendimetalina) que previenen germinación, (3) control mecánico con cultivadores de discos o cinceles en surcos, (4) labranza reducida con rastrojo que suprime germinación de malezas anuales, (5) monitoreo temprano para detectar escapes y manejarlos antes de que semillen, (6) cultivos de cobertura en invierno que compiten con malezas. La dosis recomendada de glifosato es 2-3 L/ha de producto comercial, aplicado con agua dura (pH >7) requiere ajuste con sulfato de amonio (5 kg/200 L).', labels: ['plagas', 'cultivos'] },
  { title: 'Implementación de techos verdes y huertos urbanos para seguridad alimentaria', body: 'Los techos verdes productivos integran agricultura urbana con beneficios ambientales en ciudades colombianas. La estructura requiere: impermeabilización, capa drenante (grava volcánica o arcilla expandida 5-10 cm), geotextil, sustrato ligero (30% compost + 30% fibra de coco + 40% perlita, profundidad 15-30 cm). Las especies recomendadas son: lechuga, espinaca, acelga, rábano, hierbas aromáticas (albahaca, cilantro, menta, orégano) y frutales enanos (limón, fresa, tomate cherry). El riego por goteo con temporizador es esencial (2-4 L/m²/día en clima cálido). Un techo verde de 50 m² puede producir 150-300 kg de hortalizas al año. Los beneficios incluyen: reducción de la temperatura interior en 3-5°C, captación de agua lluvia (50-70% de la precipitación), mejora de la calidad del aire y producción de alimentos locales.', labels: ['cultivos', 'suelos'] },

  // ── Café: Equipo y Procesamiento ──
  { title: 'Manejo de la broca del café en época de postcosecha y almacenamiento', body: 'La broca del café (Hypothenemus hampei) sobrevive en frutos secos que quedan en el árbol y en el suelo después de la cosecha principal. El manejo en postcosecha es crítico para reducir poblaciones: (1) realizar una recolección sanitaria (pepena) de todos los frutos que quedaron en árboles y suelo, (2) eliminar frutos brocados mediante inmersión en agua (los frutos brocados flotan por tener menor densidad), (3) aplicar Beauveria bassiana (1 kg/ha) al suelo y árboles después de la pepeña, (4) mantener el café almacenado con humedad <12% (la broca no se reproduce con humedad inferior a 13%), (5) almacenar en silos herméticos con atmósfera modificada (CO2 >20%) o en sacos de polipropileno tratados con deltametrina (0.1 g/m²). La exposición al sol directo de frutos brocados elimina las larvas internas por deshidratación.', labels: ['café', 'plagas', 'cultivos', 'cosecha'] },
  { title: 'Calibración de refractómetro para medición de grados Brix en frutas', body: 'El refractómetro mide los sólidos solubles totales (SST) expresados en grados Brix, indicador del contenido de azúcares y del punto óptimo de cosecha. La calibración se realiza con agua destilada (0°Brix a 20°C) ajustando el tornillo de calibración hasta que la línea limite marque exactamente 0. Los valores óptimos de Brix para cosecha son: mango 12-16°Brix, banano 20-24°Brix, naranja 10-14°Brix, uva 18-24°Brix, tomate 4-6°Brix, lulo 7-9°Brix, fresa 7-10°Brix. La temperatura afecta la lectura: si la muestra está a temperatura diferente a 20°C, se debe aplicar un factor de corrección (sumar 0.5°Brix por cada 5°C por encima de 20°C). Para zumos de fruta ácida, se recomienda filtrar antes de medir para evitar partículas que interfieran con la lectura.', labels: ['cosecha', 'cultivos'] },
  { title: 'Diseño e implementación de un vivero agroecológico para la producción de plántulas', body: 'El vivero agroecológico debe ubicarse cerca de fuente de agua, con topografía plana y protegido de vientos fuertes. El diseño incluye: (1) área de germinación con camas a 50 cm del suelo y sustrato esterilizado (arena + tierra + compost 1:1:1), (2) área de crecimiento con bolsas de 15x20 cm dispuestas en eras de 1.2 m de ancho, (3) sistema de riego por microaspersión (caudal 4 mm/día), (4) media sombra (rastrelo al 50-60%) regulable según etapa del cultivo, (5) área de compostaje para producción de sustrato, (6) zona de cuarentena para plantas sospechosas de enfermedades. Las condiciones óptimas de manejo: temperatura 20-30°C, humedad relativa 60-80%, riego en horas de la mañana. La densidad de bolsas es 40-50/m². El tiempo de permanencia de plántulas en vivero varía: 2-3 meses para hortalizas, 3-6 meses para café y cacao, 1-2 años para frutales.', labels: ['cultivos'] },

  // ── Plagas: Mosca de la fruta ──
  { title: 'Manejo integrado de la mosca de la fruta (Ceratitis capitata, Anastrepha spp.) en frutales', body: 'Las moscas de la fruta causan pérdidas de 20-50% en frutales colombianos si no se manejan. Las especies más importantes son Anastrepha obliqua (mango, guayaba), Anastrepha striata (guayaba) y Ceratitis capitata (cítricos). El monitoreo se realiza con trampas McPhail cebadas con proteína hidrolizada (cebo atrayente al 5%). El umbral de acción es 1 mosca/trampa/día. El manejo integrado incluye: (1) recolección semanal de frutos caídos enterrándolos a 30 cm de profundidad, (2) aplicación de cebo tóxico (proteína hidrolizada 5% + Malatión 0.5%) en parches de 50x50 cm cada 10 árboles, (3) liberación de parasitoides de larvas (Diachasmimorpha longicaudata) a razón de 400 adultos/ha/semana, (4) embolse de frutos en árboles pequeños, (5) trampeo masivo con 50 trampas/ha en época de fructificación.', labels: ['plagas', 'frutales', 'cultivos'] },
  { title: 'Manejo de la moniliasis del cacao en la Amazonía colombiana', body: 'La moniliasis en la Amazonía colombiana presenta características particulares por la alta humedad (>85% HR) y temperaturas constantes (24-28°C) que favorecen el patógeno. Las estrategias específicas para la región incluyen: (1) distanciamientos mayores (4x4 m, 625 plantas/ha) para mejorar la circulación de aire, (2) podas más intensas (eliminar 40% del dosel) para reducir la humedad interna, (3) aplicación de fungicida biológico Trichoderma viride (2x10^12 esporas/ha) cada 8 días en época de lluvias, (4) eliminación de frutos enfermos cada 5 días (vs 7-10 días en otras regiones), (5) uso de clones tolerantes como ICS-95, CCN-51 y FSA-12 desarrollado por Corpoica. La implementación del sistema de poda semanal con eliminación de frutos enfermos reduce la incidencia de 60% a menos de 15% en 2 ciclos de cultivo.', labels: ['cacao', 'plagas', 'cultivos'] },
  { title: 'Pastoreo racional Voisin: principios y aplicación en fincas ganaderas', body: 'El Pastoreo Racional Voisin (PRV) se basa en 4 leyes universales: (1) tiempo de ocupación máximo 3-4 días en época de lluvias y 5-7 días en época seca, (2) tiempo de descanso suficiente para que la planta se recupere (30-60 días según especie y época), (3) carga animal adecuada (alta densidad, 50-200 UGG/ha durante la ocupación), (4) pastoreo en el momento óptimo del pasto (3-5 hojas por macolla para Brachiaria, altura 25-35 cm). La implementación requiere dividir potreros grandes (10-50 ha) en parcelas de 0.5-2 ha con cerca eléctrica. La capacidad de carga aumenta de 0.5-1.0 UGG/ha en pastoreo continuo a 2.5-4.0 UGG/ha en PRV con pastos mejorados. La productividad por hectárea se multiplica por 3-5 veces en producción de carne y leche, con menor uso de concentrados y fertilizantes.', labels: ['cultivos', 'suelos'] },
  { title: 'Elaboración de abono tipo bocashi: fermentación aeróbica de residuos', body: 'El bocashi es un abono orgánico fermentado que se prepara en 12-15 días. Ingredientes (por tonelada): 500 kg de material vegetal (hojas, rastrojo, tusa de maíz), 300 kg de estiércol bovino, 100 kg de salvado de arroz o trigo, 50 kg de carbón vegetal molido, 30 kg de melaza o miel de purga, 10 L de microorganismos eficientes (EM), 10 kg de cal agrícola, 10 kg de roca fosfórica. La preparación consiste en mezclar todos los ingredientes con humedad del 40-50% (prueba del puño). La pila (1 m de alto) se voltea cada 12 horas los primeros 3 días y cada 24 horas hasta el día 12. La temperatura debe alcanzar 55-65°C en las primeras 48h (fase termofílica), luego descender gradualmente a 35-40°C. El bocashi maduro presenta olor a fermentado agradable, textura friable y pH 7.0-7.5. Se aplica 1-2 kg/m² en cultivos intensivos.', labels: ['suelos', 'nutrición', 'cultivos'] },
  { title: 'Manejo de la mosca blanca en cultivos de tomate bajo invernadero', body: 'La mosca blanca (Trialeurodes vaporariorum) en tomate bajo invernadero requiere manejo intensivo por su capacidad de desarrollar resistencia a insecticidas. El manejo integrado incluye: (1) exclusión física con malla anti-áfidos (50 mesh) en ventilaciones y doble puerta, (2) monitoreo semanal con trampas amarillas (20/ ha) y revisión del envés de hojas (muestrear 10 plantas/1000 m²), (3) liberación de Encarsia formosa a razón de 5-10 adultos/m² cada 8-15 días durante 6-8 semanas, (4) aplicación de hongo Lecanicillium lecanii (10^12 conidias/ha) al anochecer, (5) aplicaciones dirigidas de Beauveria bassiana + aceite agrícola 0.5% en infestaciones >5 adultos/hoja, (6) jabón potásico (2%) como coadyuvante en todas las aplicaciones, (7) eliminación de malezas hospederas dentro y fuera del invernadero, (8) periodos de vacío sanitario de 15-30 días entre ciclos de cultivo.', labels: ['plagas', 'cultivos'] },
  { title: 'Conservación de suelos en cultivos de papa en páramo', body: 'El cultivo de papa en zonas de páramo (>3000 m) requiere prácticas especiales de conservación por la fragilidad del ecosistema y la pendiente del terreno. Las prácticas obligatorias incluyen: (1) siembra en curvas a nivel con surcos en contorno, (2) barreras vivas con pasto kikuyo o avena forrajera cada 10-15 m, (3) acequias de infiltración o zanjas de ladera, (4) cobertura del suelo con residuos de papa (rastrojo) después de la cosecha, (5) mínimo laboreo (solo en el surco de siembra), (6) aplicación de compost en lugar de fertilizante químico para reducir la lixiviación de nitratos a fuentes de agua. La rotación con avena forrajera o lupino por 2-3 años entre ciclos de papa restaura la fertilidad y rompe ciclos de plagas. El uso de maquinaria pesada en páramo está restringido por la Resolución 129/2015 del Ministerio de Ambiente.', labels: ['suelos', 'cultivos'] },
  { title: 'Implementación de invernaderos de bajo costo para la producción de hortalizas', body: 'Los invernaderos de bajo costo tipo capilla (4 m de ancho, 2.5 m de altura) se construyen con materiales locales: estructura de guadua (Bambusa guadua) tratada con bórax-ácido bórico (5%), cubierta de plástico calibre 6 (200 micras) con tratamiento UV, y sujeción con tiras de caucho. La orientación recomendada es este-oeste para maximizar la captación de luz en el día. El sistema de ventilación incluye ventanas laterales enrollables (abertura 30% del área del piso) más cumbrera cenital. El costo de construcción es USD 10-15/m² (vs USD 30-60/m² de invernaderos comerciales). La producción en invernadero aumenta 2-3 veces sobre campo abierto, reduce el uso de plaguicidas en 50-70% y permite producción durante todo el año. Se recomienda la rotación de cultivos cada ciclo: tomate → fríjol → lechuga → pimentón.', labels: ['cultivos'] },
  { title: 'Caracterización y manejo de suelos sulfatados ácidos en la Orinoquía colombiana', body: 'Los suelos sulfatados ácidos de la Altillanura plana (Llanos Orientales) presentan pH 3.5-4.5, alta saturación de aluminio (>60%) y baja CIC (<5 cmol/kg). El manejo para incorporarlos a la producción agrícola requiere: (1) encalamiento profundo con cal dolomítica (2-5 ton/ha) incorporada a 30-40 cm de profundidad, (2) aplicación anual de yeso agrícola (1-2 ton/ha) para reducir Al intercambiable y aportar Ca, (3) uso de variedades tolerantes a acidez (arroz Llanura-11, soya BR-36, maíz ICA V-305), (4) fertilización con fósforo (80-120 kg P2O5/ha) por su alta fijación en suelos ácidos, (5) inoculación con bacterias fijadoras de N (Azospirillum, Bradyrhizobium) adaptadas a condiciones ácidas, (6) siembra de especies mejoradoras como Brachiaria humidicola o Stylosanthes capitata para acelerar la recuperación del suelo. El proceso de corrección toma 3-5 años.', labels: ['suelos', 'cultivos'] },
  { title: 'Manejo de trips en cultivos de cebolla de rama (Allium fistulosum)', body: 'Los trips (Thrips tabaci) causan daños por raspado de tejido en cebolla de rama, dejando manchas plateadas (plateado) que reducen la calidad comercial. El monitoreo se realiza revisando 20 plantas al azar y contando trips en las axilas de las hojas (umbral: 10 trips/planta). El manejo integrado incluye: (1) aplicación de aceite de neem (0.5%) cada 8-10 días como preventivo, (2) liberación de Amblyseius swirskii (50 ácaros/m²) en plantaciones comerciales, (3) aplicación de hongos entomopatógenos Metarhizium anisopliae (2x10^13 conidias/ha) al suelo para controlar pupas, (4) insecticidas selectivos en poblaciones altas: Spinosad (0.3 mL/L) o Abamectina (0.5 mL/L), (5) láminas de agua en los surcos para crear microclima adverso a los trips, (6) eliminación de residuos de cosecha que sirven de refugio. La rotación de ingredientes activos cada 2 aplicaciones evita resistencia.', labels: ['plagas', 'cultivos'] },
  { title: 'Estrategias de adaptación al cambio climático en la caficultura colombiana', body: 'La caficultura colombiana enfrenta los efectos del cambio climático: aumento de temperatura (1.5-2.5°C al 2050), cambio en patrones de lluvia y mayor incidencia de plagas y enfermedades. Las estrategias de adaptación incluyen: (1) ascenso de cultivos a mayores altitudes (200-300 m por encima del rango tradicional), (2) renovación con variedades tolerantes al estrés hídrico como Castillo® regional, (3) establecimiento de sistemas agroforestales con sombrío regulado (30-50%) que reduce temperatura del microclima en 3-5°C, (4) cosecha de agua lluvia en reservorios (100-200 m³/ha) para riego de auxilio en veranos prolongados, (5) diversificación de ingresos con plátano, cítricos o aguacate asociados, (6) seguros agroclimáticos indexados (Fasecolda) que cubren pérdidas por eventos extremos, (7) sistemas de alerta temprana para plagas (broca, roya) basados en modelos climáticos de Cenicafé.', labels: ['café', 'cultivos', 'clima'] },

  // ── Cacao: Clones y Postcosecha ──
  { title: 'Evaluación sensorial del cacao: protocolo de cata y perfiles de sabor', body: 'El protocolo de cata de cacao sigue la metodología de la Fine Chocolate Industry Association (FCIA). La prueba de corte evalúa: (1) color del grano (marrón púrpura = buena fermentación, violeta = fermentación incompleta, pizarroso = sin fermentar), (2) estructura interna (grano bien desarrollado con cutícula definida). La cata profesional evalúa: aroma (notas a fruta, caramelo, nuez, floral, té, tabaco), sabor básico (acidez, amargor, astringencia, dulzor), notas específicas (frutos rojos, cítricos, tropicales, madera), textura (derretimiento, untuosidad, granulosidad) y persistencia (final de boca). Los perfiles de cacao colombiano incluyen: Sierra Nevada (notas a caramelo, nuez, baja acidez), Santander (cítrico, floral, acidez brillante), Tumaco (cacao base, notas a madera, amargor moderado), Amazonía (especias, frutas rojas, acidez compleja).', labels: ['cacao', 'cultivos', 'cosecha'] },
  { title: 'Control del hongo ceratocystis (Ceratocystis fimbriata) en cacao', body: 'Ceratocystis fimbriata causa la muerte descendente en cacao, obstruyendo los vasos del xilema y causando marchitez foliar irreversible. Los síntomas incluyen amarillamiento foliar progresivo, marchitez de ramas y muerte del árbol en 3-6 meses. El manejo se basa en prevención estricta: (1) eliminación y quema de árboles infectados, incluyendo raíces, (2) desinfección de herramientas de poda con hipoclorito (10%) o alcohol (70%) entre cada árbol, (3) evitar heridas en tronco y raíces durante labores culturales, (4) aplicación de pasta fungicida (oxicloruro de cobre + cal) en heridas de poda mayores a 2 cm, (5) control de insectos vectores (escarabajos ambrosiales, Xyleborus spp.) con trampas de alcohol, (6) establecimiento de barreras de protección con árboles no hospedantes alrededor del lote. No existe control químico curativo una vez establecida la infección vascular.', labels: ['cacao', 'plagas', 'cultivos'] },

  // ── Plátano: más plagas y manejo ──
  { title: 'Manejo del virus del rayado del banano (BSV) en musáceas', body: 'El virus del rayado del banano (BSV, Banana streak virus) se transmite por cochinillas harinosas (Planococcus spp. y Saccharicoccus spp.) y por material vegetal infectado. Los síntomas incluyen rayas cloróticas necróticas en hojas que corren paralelas a las nervaduras. El manejo preventivo incluye: (1) uso de colinos certificados libres de virus (análisis PCR obligatorio), (2) control de cochinillas vectores con aplicaciones de aceite agrícola (1%) + jabón potásico (0.5%) cada 15 días, (3) control biológico de cochinillas con Cryptolaemus montrouzieri (10 adultos/árbol en focos), (4) eliminación de plantas con síntomas severos (roguing) en etapas tempranas, (5) cuarentena para material vegetal introducido de otras regiones, (6) monitoreo molecular (PCR) cada 6 meses en lotes de multiplicación de semilla. En variedades como FHIA-20, la incidencia puede alcanzar 30% en condiciones de alta presión del vector.', labels: ['plátano', 'plagas', 'cultivos'] },
  { title: 'Control biológico de picudo negro en plátano con hongos entomopatógenos', body: 'Los hongos entomopatógenos para control de Cosmopolites sordidus se aplican de forma combinada. Beauveria bassiana cepa Bb-CS1 (aislada de picudo) se aplica a 2x10^13 conidias/ha en el suelo alrededor del cormo, con dosis de 50 g de formulación comercial en 20 L de agua, aplicando 200 mL/planta. Metarhizium anisopliae cepa Ma-CS2 complementa en suelos con alta humedad. Las trampas de pseudotallo se impregnan con una suspensión de 20 g de conidias/L de agua + 0.1% de Tween 80 como adherente. La eficacia combinada (hongos + trampeo masivo) alcanza 65-80% de reducción poblacional en 6 meses. Las aplicaciones deben repetirse cada 3-4 meses, preferiblemente en épocas de lluvia cuando la humedad del suelo favorece la germinación de conidias y la infección de adultos.', labels: ['plátano', 'plagas', 'cultivos'] },
  { title: 'Manejo de coberturas vegetales en cultivos de cacao para el control de arvenses', body: 'Las coberturas vegetales en cacao reducen la competencia de arvenses a la vez que mejoran el suelo. Las especies recomendadas incluyen: Arachis pintoi (maní forrajero, cobertura densa de 15-20 cm, tolerante a sombra), Desmodium ovalifolium (cobertura de 30-50 cm, fijación N), Pueraria phaseoloides (kudzú, crecimiento rápido, 100-150 kg N/ha/año), y Calopogonium mucunoides (calopo, resistente a sequía). La siembra de coberturas se realiza al inicio de la época de lluvias, a 50x50 cm entre plantas, sembrando 5-8 kg/ha de semilla escarificada. Las coberturas requieren control inicial de arvenses agresivas durante los primeros 2-3 meses. Los beneficios incluyen: reducción de la temperatura del suelo (3-5°C), conservación de humedad (20-30% más retención, mayor actividad biológica y aporte de 5-10 ton MS/ha/año de biomasa.', labels: ['cacao', 'suelos', 'cultivos'] },
  { title: 'Polinización manual del cacao: técnica y eficiencia', body: 'La polinización manual del cacao puede aumentar el cuajado de frutos de 5-10% (polinización natural) a 60-80%. El cacao es polinizado por insectos pequeños (Ceratopogonidae: Forcipomyia spp.) que son ineficientes en monocultivos extensivos. La técnica manual consiste en: (1) recolectar flores frescas (abiertas el mismo día) con anteras dehiscentes (polen maduro), (2) tomar el polen de las anteras con un pincel fino de pelo de camello, (3) depositar el polen en el estigma de flores receptivas (estilo con gotita de secreción estigmática), (4) polinizar 20-30 flores/árbol en árboles adultos, (5) repetir cada 3-4 días durante el pico de floración. La ventana de receptividad del estigma es de 6-12 horas después de la apertura de la flor. La polinización manual es rentable en clones de alto valor como ICS-95 o CCN-51 donde cada fruto extra representa 30-50 g de grano seco de alta calidad.', labels: ['cacao', 'cultivos'] },
];

async function main() {
  console.log(`Iniciando siembra de ${posts.length} posts en el foro...\n`);

  // Buscar o crear un usuario seed para los posts
  let authorId = process.env.FORUM_SEED_USER_ID;

  if (!authorId) {
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@agroecotopia.com';
    let user = await prisma.user.findFirst({ where: { email: adminEmail } });
    if (!user) {
      user = await prisma.user.findFirst({ where: { role: 'admin' } });
    }
    if (!user) {
      user = await prisma.user.findFirst({ orderBy: { createdAt: 'asc' } });
    }
    if (!user) {
      console.log('No se encontró ningún usuario. Creando un usuario seed...');
      const seedEmail = `seed-${randomUUID()}@agroecotopia.com`;
      user = await prisma.user.create({
        data: {
          name: 'Semilla Foro Agroecotopia',
          email: seedEmail,
          role: 'admin',
        },
      });
      console.log(`  ✓ Usuario seed creado: ${user.email} (${user.id})`);
    }
    authorId = user.id;
  }

  console.log(`  Usando autor: ${authorId}\n`);

  let created = 0;
  let errors = 0;

  for (let i = 0; i < posts.length; i++) {
    const p = posts[i];
    try {
      await prisma.forumPost.create({
        data: {
          title: p.title,
          body: p.body,
          labels: p.labels,
          authorId,
        },
      });
      created++;
      process.stdout.write(`  ✓ ${String(i + 1).padStart(2, '0')}/${posts.length} "${p.title.substring(0, 70)}..."\n`);
    } catch (e: any) {
      errors++;
      process.stdout.write(`  ✗ ${String(i + 1).padStart(2, '0')}/${posts.length} "${p.title.substring(0, 50)}": ${e.message.substring(0, 80)}\n`);
    }
  }

  const total = await prisma.forumPost.count();
  console.log(`\nResultado:`);
  console.log(`  Creados: ${created}`);
  console.log(`  Errores: ${errors}`);
  console.log(`  Total en foro: ${total}`);

  // Generar embeddings para los posts creados (si Ollama está disponible)
  console.log(`\nGenerando embeddings vectoriales...`);
  const { ForumPostEmbeddingService } = await import('@/backend/modules/forum/forumPostEmbedding.service');
  const embeddingService = new ForumPostEmbeddingService();
  const result = await embeddingService.generateAll();
  console.log(`  Embeddings generados: ${result.success}`);
  console.log(`  Fallos: ${result.failed}`);
  console.log(`  Omitidos: ${result.skipped}`);

  await prisma.$disconnect();
  console.log(`\n✨ Seed completado.`);
}

main().catch(console.error);
